# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onesignal-email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onesignalemailprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onesignal_email_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
