# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onesignal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
