# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onesignal', '0002_auto_20180504_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
