# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailprofile',
            table=None,
        ),
    ]
