# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20180731_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
