# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0004_auto_20180504_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
