# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_emailprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mailing_profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
