# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courier', '0006_auto_20180508_0039'),
    ]

    operations = [
    ]

    database_operations = [migrations.AlterModelTable('EmailProfile', 'emails_emailprofile')]

    state_operations = [migrations.DeleteModel('EmailProfile')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
